In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Numpy merupakan Library Pyhton digunakan untuk komputasi matriks
Matplotlib merupakan Library Pyhton untuk presentasi data berupa grafik
Numpy merupakan Library Pyhton digunakan untuk komputasi matriks Matplotlib merupakan Library Pyhton untuk presentasi data berupa grafik

In [2]:
dataset = pd.read_csv('car_data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
print(x)

[[385 'Male' 35.0 nan]
 [681 'Male' 40.0 43500.0]
 [353 'Male' 49.0 74000.0]
 ...
 [407 'Female' 28.0 138500.0]
 [299 'Female' 48.0 134000.0]
 [687 'Female' 44.0 73500.0]]


In [4]:
print(y)

[0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0
 1 1 0 0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 0 0
 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1
 0 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1
 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0
 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 0
 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 0 0 0
 1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1
 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1
 0 0 0 0 1 0 1 1 1 0 0 1 

In [5]:
from itertools import starmap
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,3:4])
x[:,3:4] = imputer.transform(x[:,3:4])

In [6]:
print(x)

[[385 'Male' 35.0 72655.08559919435]
 [681 'Male' 40.0 43500.0]
 [353 'Male' 49.0 74000.0]
 ...
 [407 'Female' 28.0 138500.0]
 [299 'Female' 48.0 134000.0]
 [687 'Female' 44.0 73500.0]]


ct adalah variabel yang digunakan untuk memanggil kolom transformes, dimana mengubah kolom transformers dari nominal ke bentuk matriks dengan cara di encoder dengan function onehotencoder

kemudian ubah format menjadi array menggunakan numpy array

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 385 35.0 72655.08559919435]
 [0.0 1.0 681 40.0 43500.0]
 [0.0 1.0 353 49.0 74000.0]
 ...
 [1.0 0.0 407 28.0 138500.0]
 [1.0 0.0 299 48.0 134000.0]
 [1.0 0.0 687 44.0 73500.0]]


In [9]:
print(y)

[0 0 0 1 0 1 1 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0
 1 1 0 0 1 0 0 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 0 0
 1 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1
 0 0 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 1 1 0 0 1 1
 1 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0
 0 0 0 0 1 1 0 0 0 0 1 0 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 1 0 0
 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 0
 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0
 0 1 0 1 0 1 0 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 0 1 1 1 0 0 0 0
 1 1 0 0 0 0 1 0 1 1 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1
 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 1
 0 0 0 0 1 0 1 1 1 0 0 1 

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x,y, test_size=0.2, random_state=1)

In [11]:
print(x_train)

[[0.0 1.0 77 19.0 70000.0]
 [1.0 0.0 951 53.0 104000.0]
 [0.0 1.0 946 39.0 60500.0]
 ...
 [0.0 1.0 508 36.0 54500.0]
 [1.0 0.0 1000 40.0 76500.0]
 [1.0 0.0 249 39.0 114500.0]]


In [12]:
print(x_test)

[[1.0 0.0 587 30.0 79000.0]
 [1.0 0.0 839 38.0 79500.0]
 [0.0 1.0 896 43.0 77500.0]
 [1.0 0.0 867 42.0 73500.0]
 [0.0 1.0 613 36.0 92500.0]
 [0.0 1.0 608 43.0 59500.0]
 [0.0 1.0 131 42.0 65000.0]
 [0.0 1.0 705 43.0 65500.0]
 [0.0 1.0 879 36.0 73500.0]
 [1.0 0.0 27 40.0 60500.0]
 [0.0 1.0 763 26.0 32000.0]
 [0.0 1.0 520 57.0 72500.0]
 [0.0 1.0 39 19.0 83500.0]
 [0.0 1.0 153 39.0 106000.0]
 [1.0 0.0 844 36.0 48500.0]
 [1.0 0.0 450 36.0 75000.0]
 [0.0 1.0 225 26.0 16000.0]
 [1.0 0.0 219 46.0 132500.0]
 [1.0 0.0 37 22.0 27000.0]
 [0.0 1.0 140 47.0 80500.0]
 [0.0 1.0 161 42.0 53500.0]
 [1.0 0.0 537 41.0 51000.0]
 [1.0 0.0 256 37.0 80000.0]
 [0.0 1.0 198 32.0 18000.0]
 [1.0 0.0 541 21.0 68000.0]
 [0.0 1.0 438 28.0 59000.0]
 [1.0 0.0 511 18.0 44000.0]
 [0.0 1.0 538 33.0 31000.0]
 [0.0 1.0 115 40.0 61000.0]
 [1.0 0.0 625 29.0 56500.0]
 [0.0 1.0 818 48.0 35500.0]
 [0.0 1.0 503 35.0 73000.0]
 [1.0 0.0 595 40.0 142000.0]
 [0.0 1.0 5 41.0 108500.0]
 [1.0 0.0 220 30.0 116000.0]
 [1.0 0.0 68 35.0 44

In [13]:
print(y_train)

[0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 0 0
 0 0 0 0 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 0 0 1 0 0
 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0
 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 0 0 0 0
 1 0 1 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1
 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 1 0 1 0 0 0 1 1 0 1 1 0 0 1
 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1
 0 0 0 1 1 1 1 0 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1 1 0 0 1 0 0 1 0 1
 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 1
 1 0 0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 0
 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1
 0 1 0 1 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 1 1
 0 0 0 0 0 1 0 0 1 1 1 0 

In [14]:
print(y_test)

[0 1 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1
 0 1 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0
 1 0 0 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 0 1 1 0 1 0 0
 0 0 1 0 0 1 0 1 1 1 1 1 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 0
 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 0
 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0]


In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 2:] = sc.fit_transform(x_train[:,2:])
x_test[:, 2:] = sc.fit_transform(x_test[:,2:])

In [16]:
print(x_train)

[[0.0 1.0 -1.50490066036679 -1.993936612190505 -0.09199278485000335]
 [1.0 0.0 1.5729910917479557 1.1999495426582065 0.8812162552162459]
 [0.0 1.0 1.5553830153628598 -0.1151800505147924 -0.3639188401626318]
 ...
 [0.0 1.0 0.012915524028467833 -0.3969935347661493 -0.5356616119390287]
 [1.0 0.0 1.7455502403218945 -0.02124222243100676 0.09406188457442664]
 [1.0 0.0 -0.8991828327194946 -0.1151800505147924 1.1817661058249405]]


In [17]:
print(x_test)

[[1.0 0.0 0.33241942419297027 -0.8691298207629892 0.2726815418032617]
 [1.0 0.0 1.155062013769996 -0.13858353002662246 0.28857207454237954]
 [0.0 1.0 1.34113593284099 0.31800790168360676 0.22500994358590828]
 [1.0 0.0 1.246466745945221 0.2266896153415609 0.09788568167296574]
 [0.0 1.0 0.41729524692710784 -0.32122010271071416 0.7017259257594427]
 [0.0 1.0 0.4009729733243891 0.31800790168360676 -0.3470492350223331]
 [0.0 1.0 -1.156171928374981 0.2266896153415609 -0.17225337489203713]
 [0.0 1.0 0.7176250812171331 0.31800790168360676 -0.15636284215291932]
 [0.0 1.0 1.2856402025917462 -0.32122010271071416 0.09788568167296574]
 [1.0 0.0 -1.4956752193115312 0.04405304265746922 -0.3152681695440975]
 [0.0 1.0 0.9069634550086708 -1.2344029661311726 -1.221028535673813]
 [0.0 1.0 0.11370095791653886 1.5964639104722484 0.06610461619473011]
 [0.0 1.0 -1.4565017626650063 -1.8736309705254934 0.41569633645532206]
 [0.0 1.0 -1.0843539245230185 -0.04726524368457662 1.1307703097156239]
 [1.0 0.0 1.1713842